apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-k8s
  name: hello-k8s
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - image: nginx
    name: hello-k8s
    ports:
    - containerPort: 80
